POST http://localhost:8080/category HTTP/1.1
Content-Type: application/json

{
    "name": "test 2"
}

###

GET http://localhost:8080/category/ab3bdd9c-ef02-41e3-9e22-d640f1e58d0f HTTP/1.1
Content-Type: application/json

###

GET http://localhost:8080/category HTTP/1.1
Content-Type: application/json

###

POST http://localhost:8080/product HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
    "name": "Product 1",
    "description": "Product 1 description",
    "price": 100,
    "category_id": "d8fc81eb-aeb8-42eb-b238-4f71e21873ec",
    "image_url": "http://www.google.com"
}

###

GET http://localhost:8080/product HTTP/1.1
Host: localhost:8080
Content-Type: application/json

###

GET http://localhost:8080/product/0d9c6f2c-7191-419b-a6aa-fbd2ba40a71d HTTP/1.1
Host: localhost:8080
Content-Type: application/json

### 

GET http://localhost:8080/product/category/d8fc81eb-aeb8-42eb-b238-4f71e21873ec HTTP/1.1
Host: localhost:8080
Content-Type: application/json